### ISSUE TITLE
Build a Wheel

### ISSUE THREAD

**Issue by bzlibby** [bzlibby/sims-wheel#1]
- [x] [Title bar](https://github.com/bzlibby/SimsWheel/issues/2#issue-651966987)
- [x] [Form to select packs owned](https://github.com/bzlibby/SimsWheel/issues/3#issue-651968135)
- [x] [Spin the wheel & show results](https://github.com/bzlibby/SimsWheel/issues/4#issue-651969145)
- [x] [Fields to display results](https://github.com/bzlibby/SimsWheel/issues/5#issue-651970840)
- [x] [Credit](https://github.com/bzlibby/SimsWheel/issues/6#issue-651971333)
- [ ] [Host a wheel](https://github.com/bzlibby/SimsWheel/issues/7#issue-651971544)
